# Copyright 2026 The Yee Authors
# BSD-style license in LICENSE. Original resources retain their own licenses.
community_scriptlet_sources = [
  "data/community/brave-resources/LICENSE",
  "data/community/brave-resources/metadata.json",
  "data/community/brave-resources/resources/async-sugarcoat-04394153a7ce417b88e3fe1790a4e6a269bfebe5.js",
  "data/community/brave-resources/resources/async-sugarcoat-8a459c41783885dc83d30f5b7da2359091f4e607.js",
  "data/community/brave-resources/resources/brave-auto-pip.js",
  "data/community/brave-resources/resources/brave-disable-pageview-api.js",
  "data/community/brave-resources/resources/brave-fix.js",
  "data/community/brave-resources/resources/brave-google-maps-fix.js",
  "data/community/brave-resources/resources/brave-video-bg-play-update.js",
  "data/community/brave-resources/resources/brave-video-bg-play.js",
  "data/community/brave-resources/resources/brave-youtube-navigation-fix.js",
  "data/community/brave-resources/resources/brave-youtube-playback-speed-fix.js",
  "data/community/brave-resources/resources/brave-youtube-theater-fix.js",
  "data/community/brave-resources/resources/brave-yt-sabr-fix.js",
  "data/community/brave-resources/resources/de-amp.js",
  "data/community/brave-resources/resources/touch-fix.js",
  "data/community/brave-resources/resources/trusted_types.js",
  "data/community/brave-resources/resources/vaft-ublock-origin.js",
  "data/community/brave-resources/resources/video-swap-new-ublock-origin.js",
  "data/community/uBlock/LICENSE.txt",
  "data/community/uBlock/src/js/arglist-parser.js",
  "data/community/uBlock/src/js/jsonpath.js",
  "data/community/uBlock/src/js/redirect-resources.js",
  "data/community/uBlock/src/js/resources/abort-current-script.js",
  "data/community/uBlock/src/js/resources/attribute.js",
  "data/community/uBlock/src/js/resources/base.js",
  "data/community/uBlock/src/js/resources/cookie.js",
  "data/community/uBlock/src/js/resources/create-html.js",
  "data/community/uBlock/src/js/resources/href-sanitizer.js",
  "data/community/uBlock/src/js/resources/json-edit.js",
  "data/community/uBlock/src/js/resources/json-prune.js",
  "data/community/uBlock/src/js/resources/localstorage.js",
  "data/community/uBlock/src/js/resources/noeval.js",
  "data/community/uBlock/src/js/resources/object-prune.js",
  "data/community/uBlock/src/js/resources/parse-replace.js",
  "data/community/uBlock/src/js/resources/prevent-addeventlistener.js",
  "data/community/uBlock/src/js/resources/prevent-bab.js",
  "data/community/uBlock/src/js/resources/prevent-clipboard-write.js",
  "data/community/uBlock/src/js/resources/prevent-dialog.js",
  "data/community/uBlock/src/js/resources/prevent-fetch.js",
  "data/community/uBlock/src/js/resources/prevent-innerHTML.js",
  "data/community/uBlock/src/js/resources/prevent-navigation.js",
  "data/community/uBlock/src/js/resources/prevent-settimeout.js",
  "data/community/uBlock/src/js/resources/prevent-xhr.js",
  "data/community/uBlock/src/js/resources/proxy-apply.js",
  "data/community/uBlock/src/js/resources/replace-argument.js",
  "data/community/uBlock/src/js/resources/run-at.js",
  "data/community/uBlock/src/js/resources/safe-self.js",
  "data/community/uBlock/src/js/resources/scriptlets.js",
  "data/community/uBlock/src/js/resources/set-constant.js",
  "data/community/uBlock/src/js/resources/shared.js",
  "data/community/uBlock/src/js/resources/spoof-css.js",
  "data/community/uBlock/src/js/resources/stack-trace.js",
  "data/community/uBlock/src/js/resources/utils.js",
  "data/community/uBlock/src/js/resources/vod.js",
  "data/community/uBlock/src/js/urlskip.js",
  "data/community/uBlock/src/web_accessible_resources/1x1.gif",
  "data/community/uBlock/src/web_accessible_resources/2x2.png",
  "data/community/uBlock/src/web_accessible_resources/32x32.png",
  "data/community/uBlock/src/web_accessible_resources/3x2.png",
  "data/community/uBlock/src/web_accessible_resources/adthrive_abd.js",
  "data/community/uBlock/src/web_accessible_resources/amazon_ads.js",
  "data/community/uBlock/src/web_accessible_resources/amazon_apstag.js",
  "data/community/uBlock/src/web_accessible_resources/ampproject_v0.js",
  "data/community/uBlock/src/web_accessible_resources/chartbeat.js",
  "data/community/uBlock/src/web_accessible_resources/doubleclick_instream_ad_status.js",
  "data/community/uBlock/src/web_accessible_resources/empty",
  "data/community/uBlock/src/web_accessible_resources/fingerprint2.js",
  "data/community/uBlock/src/web_accessible_resources/fingerprint3.js",
  "data/community/uBlock/src/web_accessible_resources/google-analytics_analytics.js",
  "data/community/uBlock/src/web_accessible_resources/google-analytics_cx_api.js",
  "data/community/uBlock/src/web_accessible_resources/google-analytics_ga.js",
  "data/community/uBlock/src/web_accessible_resources/google-analytics_inpage_linkid.js",
  "data/community/uBlock/src/web_accessible_resources/google-ima.js",
  "data/community/uBlock/src/web_accessible_resources/googlesyndication_adsbygoogle.js",
  "data/community/uBlock/src/web_accessible_resources/googletagservices_gpt.js",
  "data/community/uBlock/src/web_accessible_resources/hd-main.js",
  "data/community/uBlock/src/web_accessible_resources/nitropay_ads.js",
  "data/community/uBlock/src/web_accessible_resources/nobab2.js",
  "data/community/uBlock/src/web_accessible_resources/noeval-silent.js",
  "data/community/uBlock/src/web_accessible_resources/noeval.js",
  "data/community/uBlock/src/web_accessible_resources/nofab.js",
  "data/community/uBlock/src/web_accessible_resources/noop-0.1s.mp3",
  "data/community/uBlock/src/web_accessible_resources/noop-0.5s.mp3",
  "data/community/uBlock/src/web_accessible_resources/noop-1s.mp4",
  "data/community/uBlock/src/web_accessible_resources/noop-vast2.xml",
  "data/community/uBlock/src/web_accessible_resources/noop-vast3.xml",
  "data/community/uBlock/src/web_accessible_resources/noop-vast4.xml",
  "data/community/uBlock/src/web_accessible_resources/noop-vmap1.xml",
  "data/community/uBlock/src/web_accessible_resources/noop.css",
  "data/community/uBlock/src/web_accessible_resources/noop.html",
  "data/community/uBlock/src/web_accessible_resources/noop.js",
  "data/community/uBlock/src/web_accessible_resources/noop.json",
  "data/community/uBlock/src/web_accessible_resources/noop.txt",
  "data/community/uBlock/src/web_accessible_resources/outbrain-widget.js",
  "data/community/uBlock/src/web_accessible_resources/piano-analytics.js",
  "data/community/uBlock/src/web_accessible_resources/popads-dummy.js",
  "data/community/uBlock/src/web_accessible_resources/popads.js",
  "data/community/uBlock/src/web_accessible_resources/prebid-ads.js",
  "data/community/uBlock/src/web_accessible_resources/scorecardresearch_beacon.js",
  "data/community/uBlock/src/web_accessible_resources/sensors-analytics.js",
]
