# Copyright 2026 The Yee Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/util/process_version.gni")
import("//testing/test.gni")

process_version("internal_url_scheme") {
  sources = [ "//chrome/app/theme/chromium/BRANDING" ]
  template_file = "internal_url_scheme.h.in"
  output = "$target_gen_dir/internal_url_scheme.h"
}

source_set("yee_branding") {
  sources = [
    "internal_urls.cc",
    "internal_urls.h",
  ]
  public_deps = [ "//url" ]
  deps = [
    ":internal_url_scheme",
    "//base",
  ]
}

test("internal_urls_unittests") {
  sources = [ "internal_urls_unittest.cc" ]
  deps = [
    ":yee_branding",
    "//base",
    "//base/test:run_all_unittests",
    "//testing/gtest",
  ]
}
