[CmdletBinding()]
param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]] $StartUrls
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$chromeBinary = if ($env:YEE_CHROME_BINARY) {
    $env:YEE_CHROME_BINARY
} else {
    Join-Path ${env:ProgramFiles} 'Google\Chrome\Application\chrome.exe'
}
$profileDir = if ($env:YEE_PILOT_PROFILE) {
    [System.IO.Path]::GetFullPath($env:YEE_PILOT_PROFILE)
} else {
    Join-Path $PSScriptRoot 'runtime\profile'
}

if (-not $StartUrls -or $StartUrls.Count -eq 0) {
    $StartUrls = @(
        'https://example.com/',
        'https://chromium.org/',
        'https://lit.dev/'
    )
}
if (-not (Test-Path -LiteralPath $chromeBinary -PathType Leaf)) {
    throw "Chrome binary not found: $chromeBinary. Set YEE_CHROME_BINARY to override it."
}

$defaultProfile = Join-Path $profileDir 'Default'
New-Item -ItemType Directory -Path $defaultProfile -Force | Out-Null
$preferences = Join-Path $defaultProfile 'Preferences'
if (-not (Test-Path -LiteralPath $preferences -PathType Leaf)) {
    Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'profile-template\Preferences') -Destination $preferences
}
New-Item -ItemType File -Path (Join-Path $profileDir 'First Run') -Force | Out-Null

$arguments = @(
    "--user-data-dir=`"$profileDir`"",
    '--no-first-run',
    '--no-default-browser-check',
    '--disable-sync',
    '--disable-features=ChromeWhatsNewUI',
    '--enable-features=VerticalTabs,VerticalTabsLaunch',
    '--install-autogenerated-theme=225,235,232',
    '--force-color-profile=srgb',
    '--new-window'
) + $StartUrls

Start-Process -FilePath $chromeBinary -ArgumentList $arguments | Out-Null
