#!/bin/zsh

set -euo pipefail

SCRIPT_DIR="${0:A:h}"
CHROME_APP="${YEE_CHROME_APP:-/Applications/Google Chrome.app}"
CHROME_BINARY="$CHROME_APP/Contents/MacOS/Google Chrome"
PROFILE_DIR="${YEE_PILOT_PROFILE:-$SCRIPT_DIR/runtime/profile}"

typeset -a START_URLS
if (( $# == 0 )); then
  START_URLS=(
    "https://example.com/"
    "https://chromium.org/"
    "https://lit.dev/"
  )
else
  START_URLS=("$@")
fi

if [[ ! -x "$CHROME_BINARY" ]]; then
  print -u2 "Chrome binary not found: $CHROME_BINARY"
  exit 1
fi

mkdir -p "$PROFILE_DIR/Default"

if [[ ! -f "$PROFILE_DIR/Default/Preferences" ]]; then
  cp "$SCRIPT_DIR/profile-template/Preferences" \
    "$PROFILE_DIR/Default/Preferences"
fi

touch "$PROFILE_DIR/First Run"

open -na "$CHROME_APP" --args \
  --user-data-dir="$PROFILE_DIR" \
  --no-first-run \
  --no-default-browser-check \
  --disable-sync \
  --disable-features=ChromeWhatsNewUI \
  --enable-features=VerticalTabs,VerticalTabsLaunch,GlassFrame:GlassTintOpacityForLightMode/0.38/GlassTintOpacityForDarkMode/0.72/GlassExpandOnHoverOpacity/0.72/GlassExpandOnHoverBlurRadius/18.0 \
  --install-autogenerated-theme=225,235,232 \
  --force-color-profile=srgb \
  --new-window "${START_URLS[@]}"
