# Copyright 2026 The Yee Authors. BSD-style license in LICENSE.
source_set("downloads") {
  sources = [
    "downloads_ui.cc",
    "downloads_ui.h",
  ]
  public_deps = [ "//chrome/browser/ui/webui/downloads" ]
  deps = [
    "../webui",
    "../webui:strings",
    "//chrome/browser/profiles:profile",
    "//components/history/core/common",
    "//components/prefs",
    "//components/yee_branding",
    "//content/public/browser",
    "//content/public/common",
  ]
}
